### ISSUE TITLE
Error while trying to fetch Reviews

### ISSUE THREAD

**Issue by Schiriki** [bronhy/google-my-business-php-client#5]
Hey Guys,
i found your class while searching for a php My Buisness Solution, as the php client API for google does not include the normal My Buisness Service, just My Buisness Account Managment.

When i call the method accounts_locations_reviews->listAccountsLocationsReviews, i always get a 404 that looks like this:

` {                                                      
    "error": {                                           
      "code": 404,                                       
      "message": "Requested entity was not found.",      
      "errors": [                                        
        {                                                
          "message": "Requested entity was not found.",  
          "domain": "global",                            
          "reason": "notFound"                           
        }                                                
      ],                                                 
      "status": "NOT_FOUND"                              
    }                                                    
  }   `
  
  What exactly should be used for the $parent variable here? I tried the location name that i get per request from the Oauth Playground, i tried just the id, i tried the company name - nothing works. Would really appreciate maybe a small example!

Thanks for your work!

**Comment by bronhy** [comment]
Hey @Schiriki $parant is representing the request path in your case it is 
https://developers.google.com/my-business/reference/rest/v4/accounts.locations.reviews/get

```
GET https://mybusiness.googleapis.com/v4/{name=accounts/*/locations/*/reviews/*}
```

Ie: when searching for a location
https://developers.google.com/my-business/reference/rest/v4/accounts.locations/get

```
GET https://mybusiness.googleapis.com/v4/{name=accounts/*/locations/*}
```

```
$name = "accounts/xxxxxxxx/locations/xxxxxxxx"
$this->myBusiness->accounts_locations->get($name);
```

**Comment by Schiriki** [comment]
Thanks!

Got it to work with that and a bit of tinkering around the rest of my code. Again, many thanks for the work and the fast reply, appreciate it a lot!
