### ISSUE TITLE
This is not working anymore for new api v1 of MyBusinessBusinessInformation and MyBusinessAccountManagement etc.

### ISSUE THREAD

**Issue by Coding-007** [bronhy/google-my-business-php-client#9]

**Comment by dinwal** [comment]
Any updates on this?

**Comment by Coding-007** [comment]
For new API v1, you have to use the latest version of "google/apiclient".

**Comment by bronhy** [comment]
@dinwal @Coding-007 Looks like i had no notification setup for this project. 

As Coding said this will only work with the previous api version.

I will close this issue now if you have any further question do make a new issue.
